# Generated by Django 4.1.7 on 2023-03-10 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('layers POL', 'layers POL'), ('layers POC', 'layers POC'), ('layers DOC', 'layers DOC'), ('layers Spent', 'layers Spent'), ('Broiler DOC', 'Broiler DOC'), ('Broiler 8 weeks', 'Broiler 8 weeks'), ('Turkey DOC', 'Turkey DOC'), ('layers Table size', 'layers Table size'), ('Broiler Table Size', 'Broiler Table Size')], default='layers POL', max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('age', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=250)),
                ('info', models.TextField()),
                ('image', models.ImageField(default='default_bird.png', upload_to='birds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('maize', 'maize'), ('cassava', 'cassava'), ('yam', 'yam'), ('rice', 'rice')], default='maize', max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='default_crop.png', upload_to='crops/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('crop', 'crop'), ('animal', 'animal')], default='animal', max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
