# Generated by Django 4.1.7 on 2023-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='default_equip.png', upload_to='equipments/'),
        ),
    ]
