# Generated by Django 4.1.7 on 2023-03-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='info',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
