# Generated by Django 4.1.7 on 2023-03-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_equipment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='name',
            field=models.CharField(default='Imported Turkey', max_length=50),
        ),
        migrations.AddField(
            model_name='crop',
            name='name',
            field=models.CharField(default='Imported maize', max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='Animal feeder', max_length=50),
        ),
    ]
