# Generated by Django 4.1.7 on 2023-03-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_bird_name_crop_name_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/djkpvbgmj/raw/upload/v1/media/birds/IMG_20210513_084639_656_transcpr_ylsju7.jpg', upload_to='birds/'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/djkpvbgmj/raw/upload/v1/media/birds/IMG_20210513_084639_656_transcpr_ylsju7.jpg', upload_to='crops/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/djkpvbgmj/raw/upload/v1/media/birds/IMG_20210513_084639_656_transcpr_ylsju7.jpg', upload_to='equipments/'),
        ),
    ]
