# Generated by Django 4.1.7 on 2023-03-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_alter_bird_image_alter_crop_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/djkpvbgmj/image/upload/v1678641205/media/fog/birds/pol1_twqujq.jpg', upload_to='fog/birds/'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/djkpvbgmj/image/upload/v1678641283/media/fog/crops/con7_hyftjf.jpg', upload_to='fog/crops/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/djkpvbgmj/image/upload/v1678641351/media/fog/equipments/input7_crwgv4.jpg', upload_to='fog/equipments/'),
        ),
    ]
