# Generated by Django 4.1.7 on 2023-03-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_alter_bird_image_alter_crop_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.ImageField(default='pol1_twqujq.jpg', upload_to='fog/birds/'),
        ),
    ]
