# Generated by Django 4.1.7 on 2023-03-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_alter_bird_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fog/birds/'),
        ),
    ]
